export const styles = {
  
  page: {
    fontFamily: "'DM Sans', sans-serif",
    minHeight: "100vh",
    background: "#f5f2ee",
    color: "#1a1a1a",
  },
  header: {
    background: "#1a1a1a",
    padding: "24px 40px",
  },
  headerInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  logo: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: 28,
    color: "white",
    letterSpacing: "-0.5px",
  },
  tagline: {
    color: "#888",
    fontSize: 13,
    marginTop: 2,
  },
  statsRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  statChip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(255,255,255,0.06)",
    border: "1px solid",
    borderRadius: 20,
    padding: "4px 12px",
  },
  statDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    display: "inline-block",
  },
  statText: {
    color: "#ccc",
    fontSize: 12,
    fontWeight: 500,
  },
  main: {
    maxWidth: 1100,
    margin: "0 auto",
    padding: "32px 24px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 24,
    alignItems: "start",
  },
  card: {
    background: "white",
    borderRadius: 16,
    padding: 28,
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
  },
  cardTitle: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: 22,
    marginBottom: 20,
    color: "#111",
  },
  roomGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: 8,
    marginBottom: 20,
  },
  roomChip: {
    padding: "10px 8px",
    borderRadius: 10,
    cursor: "pointer",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  roomChipName: {
    fontSize: 12,
    fontWeight: 600,
  },
  roomChipCap: {
    fontSize: 11,
    opacity: 0.75,
  },
  formGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "#555",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  input: {
    
    border: "1.5px solid #e0ddd8",
    borderRadius: 8,
    padding: "9px 12px",
    fontSize: 14,
    color: "#1a1a1a",
    background: "#faf9f7",
    width: "100%",
  },
  timeRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 4,
  },
  errorBox: {
    marginTop: 16,
    background: "#fef2f0",
    border: "1px solid #fbc9c0",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#c0392b",
    fontSize: 13,
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    lineHeight: 1.5,
  },
  errorIcon: { fontSize: 15, marginTop: 1 },
  successBox: {
    marginTop: 16,
    background: "#f0faf6",
    border: "1px solid #a8dfc7",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#16896b",
    fontSize: 13,
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    lineHeight: 1.5,
  },
  successIcon: { fontSize: 15, marginTop: 1 },
  submitBtn: {
    marginTop: 20,
    width: "100%",
    padding: "13px",
    borderRadius: 10,
    border: "none",
    color: "white",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    letterSpacing: "0.3px",
  },
  filterRow: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
    flexWrap: "wrap",
    alignItems: "center",
  },
  clearBtn: {
    padding: "9px 14px",
    border: "1.5px solid #e0ddd8",
    borderRadius: 8,
    background: "white",
    cursor: "pointer",
    fontSize: 13,
    color: "#666",
    whiteSpace: "nowrap",
  },
  bookingList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  bookingCard: {
    background: "#faf9f7",
    borderRadius: 10,
    padding: "14px 16px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  bookingTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  roomBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: "2px 8px",
    borderRadius: 20,
    display: "inline-block",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: "0.4px",
  },
  bookingTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#111",
  },
  bookingMeta: {
    display: "flex",
    gap: 14,
    fontSize: 12,
    color: "#666",
    flexWrap: "wrap",
  },
  delBtn: {
    border: "1.5px solid #e0ddd8",
    background: "white",
    borderRadius: 6,
    width: 28,
    height: 28,
    cursor: "pointer",
    fontSize: 11,
    color: "#999",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  confirmRow: {
    marginTop: 10,
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  confirmYes: {
    padding: "5px 12px",
    background: "#e85d3a",
    color: "white",
    border: "none",
    borderRadius: 6,
    fontSize: 12,
    cursor: "pointer",
    fontWeight: 600,
  },
  confirmNo: {
    padding: "5px 12px",
    background: "white",
    color: "#333",
    border: "1.5px solid #e0ddd8",
    borderRadius: 6,
    fontSize: 12,
    cursor: "pointer",
  },
  empty: {
    textAlign: "center",
    color: "#aaa",
    padding: "40px 0",
    fontSize: 14,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 24,
  },
  modalCard: {
    background: "white",
    borderRadius: 16,
    padding: 32,
    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
    maxWidth: 400,
    width: "100%",
  },
  modalTitle: {
    fontFamily: "'DM Serif Display', serif",
    fontSize: 22,
    marginBottom: 20,
    color: "#111",
  },
  modalSubmitBtn: {
    marginTop: 20,
    width: "100%",
    padding: "13px",
    borderRadius: 10,
    border: "none",
    background: "#1a1a1a",
    color: "white",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    letterSpacing: "0.3px",
  },
  currentUserChip: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "rgba(255,255,255,0.1)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 20,
    padding: "6px 14px",
    color: "#ccc",
    fontSize: 13,
    fontWeight: 500,
  },
  logoutBtn: {
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.3)",
    borderRadius: 8,
    padding: "6px 12px",
    color: "#aaa",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
};
